---
title: "Activity 2: Linear regression diagnostics and transformations"
output: 
  rmdformats::robobook:
    css: "homework.css"
    highlight: pygments
link-citations: yes
---

## Doctors and hospitals

In this activity, you will practice checking the assumptions for linear regression models. This activity investigates the relationship between the number of doctors in a county, and the number of hospitals. The data come from a random sample of 53 counties in the US, and are contained in the `CountyHealth` dataset from the `Stat2Data` package. The dataset includes the following variables: 

* `County`: the name and state of the county
* `MDs`: the number of medical doctors in the county
* `Hospitals`: number of hospitals in the county
* `Beds`: the number of beds in the hospital

We are interested in the relationship between the number of hospitals and the number of doctors in a county. To begin, we'll assume that the relationship is linear:

$\text{doctors}_i = \beta_0 + \beta_1 \text{hospitals}_i + \varepsilon_i$

## Assumptions

When we fit a linear model, we typically make certain assumptions about the data. Common assumptions include:

* **Shape:** the true relationship is actually linear
* **Constant variance:** the noise term $\varepsilon_i$ has constant variance (also called *homoscedasticity*)
* **Normality:** $\varepsilon_i$ follows a normal distribution
* **Independence:** The error terms $\varepsilon_i$ are independent

Constant variance, normality, and independence can succinctly be written $\varepsilon_i \overset{iid}{\sim} N(0, \sigma^2)$.

**Note:** None of these assumptions is needed to actually *fit* the model (we can minimize the sum of squared residuals regardless of whether the model is reasonable). However, different assumptions are needed for different uses of the model. If we want to interpret the coefficients, we want the shape assumption to be at least approximately correct. If we want to do inference, then the constant variance, normality, and independence assumptions may be needed.

## Questions

:::{.question}
#### Question 1

Fill in the code below to fit the linear regression model, and save the fitted model as `health_lm` in R:

```r
health_lm <- lm(... ~ ..., data = ...)
```
:::

Now, to assess the shape and constant variance assumptions, we use a *residual plot*, which plots the residuals (in this case, $\text{doctors}_i - \widehat{\text{doctors}}_i$) against the fitted values (in this case, $\widehat{\text{doctors}}_i$). To get residuals and fitted values, we will use the `predict` and `residuals` functions in R. The `predict` function takes in a fitted model (in this case, `health_lm`), and outputs predictions for the observed data. The `residuals` function takes in a fitted model, and outputs the observed residuals.


:::{.question}
#### Question 2

Run the code below to make a residual plot for the fitted model:

```r
CountyHealth |>
  mutate(yhat = predict(health_lm),
         residuals = residuals(health_lm)) |>
  ggplot(aes(x = yhat, y = residuals)) +
  geom_point() +
  geom_abline(slope = 0, intercept = 0, 
              color = "blue", lwd = 1.2) +
  labs(x = "Predicted number of doctors",
       y = "Residual") +
  theme_bw()
```
:::

And to assess the normality assumption, we use a QQ plot (this is short for *quantile-quantile* plot, which means we compare the quantiles of the observed residuals to the quantiles of a normal distribution).

:::{.question}
#### Question 3

Run the code below to make a QQ plot for the fitted model:

```r
CountyHealth |>
  mutate(residuals = residuals(health_lm)) |>
  ggplot(aes(sample = residuals)) +
  geom_qq() +
  geom_qq_line() +
  labs(x = "Theoretical normal quantiles",
       y = "Observed residual quantiles") +
  theme_classic()
```
:::

Recall that:

* the shape assumption is reasonable if the residuals appear to be scattered randomly above and below 0, with no clear patterns.
* the constant variance assumption is reasonable if the band of residuals has relatively constant width.
* the normality assumption is reasonable if the QQ plot looks approximately linear (the points fall close to the line)

:::{.question}
#### Question 4

Using the residual plot and the QQ plot, assess whether the shape, constant variance, and normality assumptions are reasonable.
:::

### Transformations

What do we do when the assumptions do not appear to be satisfied? One option is to transform either the explanatory or response variable, or both. Common transformations include square roots, logs, squaring, and reciprocals. For count variables (like the number of doctors), a square root is often used.

Consider the model with the square root of doctors as the response:

$$\sqrt{\text{doctors}_i} = \beta_0 + \beta_1 \text{hospitals}_i + \varepsilon_i$$

:::{.question}
#### Question 5

Use the code below to fit the new model, and save the fitted model as `health_lm2` in R:

```r
health_lm2 <- lm(sqrt(MDs) ~ Hospitals, data = CountyHealth)
```
:::


:::{.question}
#### Question 6

Perform diagnostics with your new model and confirm that the transformation has improved the suitability of the model assumptions.
:::
