---
title: "Activity 4: Multiple regression"
output: 
  rmdformats::robobook:
    css: "homework.css"
    highlight: pygments
link-citations: yes
---

## Sparrows revisited

In this class activity, we will revisit the `Sparrows` dataset, which looks at measurements of sparrows from Kent Island. Researchers measured the weight and wing length of 116 sparrows, under three different nest conditions: control (the researchers didn't change the nest), enlarged (the researchers made the nest bigger), and reduced (the researchers made the nest smaller). The `Sparrows` data is part of the `Stat2Data` package, and contains the following variables:

* `Treatment`: nest condition (control, enlarged, or reduced)
* `Weight`: sparrow weight (in grams)
* `WingLength`: sparrow wing length (in mm)

## Questions

:::{.question}
#### Question 1

Write down the population regression model, with weight as the response, and wing length and treatment as the predictors.
:::

:::{.question}
#### Question 2

Use the following code to fit the model in R. Note that we can include multiple predictors by "adding" them together in the regression formula (we don't really add them mathematically; the `+` just means "put another predictor in the model").

```{r eval=F}
sparrow_lm <- lm(Weight ~ WingLength + Treatment, data = Sparrows)
summary(sparrow_lm)
```
:::

:::{.question}
#### Question 3

What is the average change in weight associated with a 1mm increase in wing length, for sparrows from enlarged nests?
:::

:::{.question}
#### Question 4

What is the estimated difference in weight for sparrows from enlarged vs. control nests, with the same wing length?
:::

