---
title: "Activity 3: More diagnostics and transformations"
output: 
  rmdformats::robobook:
    css: "homework.css"
    highlight: pygments
link-citations: yes
---

## Gapminder data

In this activity, we will continue working with the `gapminder` data. We are interested in the relationship between GDP and life expectancy, and we will use regression to model this relationship.

Recall that the `gapminder` data contains information on 142 different countries, measured from 1952 to 2007 in increments of five years (so countries appear multiple times in the data). The available variables are

* `country`: the name of the country
* `continent`: which continent the country is located on
* `year`: which year the data were recorded in
* `lifeExp`: the life expectancy at birth, in years
* `pop`: population of the country
* `gdpPercap`: GDP per capita, in US dollars (adjusted for inflation)

## Questions

:::{.question}
#### Question 1

One assumption that we make for linear regression models is that the observations are independent. Thinking about the gapminder data, does this assumption seem reasonable?
:::

:::{.question}
#### Question 2

Let's focus only on data from 2007. Create a new dataset, called `gapminder_2007`, which contains only the 2007 data. Use the `gapminder_2007` data for the rest of the activity.
:::

:::{.question}
#### Question 3

Fit a linear regression model with GDP per capita as the predictor, and life expectancy as the response, then create residual and QQ plots to assess the shape, constant variance, and normality assumptions. Do these assumptions seem reasonable?
:::

### Transformations

Sometimes, transformations can be used to address violations of the linear regression assumptions. We'll start by trying a log transformation. Remember that when we use logs, we usually mean the *natural* log (and the `log` function in R calculates natural logs).

:::{.question}
#### Question 4

Fit a linear regression model with log(GDP per capita) as the predictor, and life expectancy as the response.
:::

:::{.question}
#### Question 5

Create a residual plot and a QQ plot for the fitted model in question 4. Do the regression assumptions look more reasonable after the log transformation?
:::

:::{.question}
#### Question 6

Using your fitted model from question 4, what is the predicted life expectancy for a country with a GDP per capita of $20000?
:::

