---
title: "Activity 4 solutions"
format: 
  html:
    embed-resources: true
editor: source
author: "Ciaran Evans"
---

```{r include=F}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = F)
knitr::opts_chunk$set(warning = F)
library(tidyverse)
```

1.

```{r}
library(Lahman)

Teams |>
  filter(teamID == "CHN") |>
  select(yearID, HR, HRA) |>
  pivot_longer(-yearID,
               names_to = "team",
               values_to = "runs") |>
  mutate(team = ifelse(team == "HR", "Cubs", "Opponent")) |>
  ggplot(aes(x = yearID, y = runs, color = team)) +
  geom_point() +
  geom_line() +
  labs(x = "Year", y = "Runs", color = "Team") +
  theme_bw()
```

2.

```{r}
df1 <- data.frame(
  grp = c("A", "A", "B", "B"),
  sex = c("F", "M", "F", "M"),
  meanL = c(0.225, 0.47, 0.325, 0.547),
  sdL = c(0.106, 0.325, 0.106, 0.308),
  meanR = c(0.34, 0.57, 0.4, 0.647),
  sdR = c(0.0849, 0.325, 0.0707, 0.274)
)

df1 |>
  pivot_longer(-c(grp, sex),
               names_to = "stat", values_to = "value") |>
  pivot_wider(id_cols = grp,
              names_from = c(sex, stat),
              names_sep = ".",
              values_from = value)
```

3.

```{r}
df2 <- data.frame(id = rep(c(1, 2, 3), 2),
                  group = rep(c("T", "C"), each=3),
                  vals = c(4, 6, 8, 5, 6, 10))

Treat <- filter(df2, group == "T")
Control <- filter(df2, group == "C")
all <- mutate(Treat, diff = Treat$vals - Control$vals)
all
```

4.

```{r}
df2 |>
  group_by(id) |>
  summarize(diff = vals[group == "T"] - vals[group == "C"])
```


5.

```{r}
df2 |>
  pivot_wider(id_cols = id,
              names_from = group,
              values_from = vals) |>
  mutate(diff = T - C)
```

6.

```{r}
sim_results <- read.csv("https://sta279-f23.github.io/homework/sim_results.csv")
```

```{r}
sim_results |>
  mutate(across(-n, function(x) {2 - x})) |>
  rowwise() |>
  mutate(method1 = mean(c_across(contains("method1"))),
         method2 = mean(c_across(contains("method2"))),
         method3 = mean(c_across(contains("method3")))) |>
  select(n, method1, method2, method3) |>
  pivot_longer(-n, 
               names_to = "method",
               values_to = "coverage") |>
  ggplot(aes(x = n, y = coverage, color = method)) +
  geom_point() +
  geom_line() +
  labs(x = "Sample size (n)",
       y = "Coverage",
       color = "Method") +
  theme_classic()
```
